######################################################################
# Automatically generated by qmake (2.01a) Wed May 23 09:04:11 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += ut.h
FORMS += ut.ui
SOURCES += timetool.cpp ut.cpp
